{"name": "test_001_panic_cancelled_by_driver_standard_endpoint", "status": "failed", "statusDetails": {"message": "AssertionError: Step 6: Device does not show correct state in live map.", "trace": "pre_conditions = None\n\n>   ???\n\nC:\\Users\\aldo.madrid\\Documents\\AutomationExample\\Xirgo_KB1_Scripts\\Panic\\test_004_panic_seen_and_cleared_by_dispatcher.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nactual = True, expected = False, fail_string = 'Device does not show correct state in live map.'\n\n    @staticmethod\n    def verify(actual, expected, fail_string):\n>       assert actual == expected, 'Step ' + str(Report.__step_no) + ': ' + fail_string\nE       AssertionError: Step 6: Device does not show correct state in live map.\n\nLibraries\\report.py:37: AssertionError"}, "attachments": [{"name": "stdout", "source": "f51b2d5f-cd02-4e7e-b9e4-3e2d29ce52c1-attachment.txt", "type": "text/plain"}], "start": 1640216672673, "stop": 1640216672675, "uuid": "f95ea14a-acaf-4766-9291-f258e8f5bf87", "historyId": "20fc32fbf27a4c34e43a2f52646c2bd3", "testCaseId": "d741bdd4a79958e4a5eefbeca364c3b2", "fullName": "Xirgo_KB1_Scripts.f_03_Panic.test_004_panic_seen_and_cleared_by_dispatcher#test_001_panic_cancelled_by_driver_standard_endpoint", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "Xirgo_KB1_Scripts.f_03_Panic"}, {"name": "suite", "value": "test_004_panic_seen_and_cleared_by_dispatcher"}, {"name": "host", "value": "WX-AMADRID"}, {"name": "thread", "value": "14636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Xirgo_KB1_Scripts.f_03_Panic.test_004_panic_seen_and_cleared_by_dispatcher"}]}